USE [WideWorldImporters]
GO

/****** Object:  Index [IDX_Sales_Orders_OrderDate]    Script Date: 4/8/2025 8:28:56 AM ******/
CREATE NONCLUSTERED INDEX [IDX_Sales_Orders_OrderDate] ON [Sales].[Orders]
(
	[OrderDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [USERDATA]
GO


